  build:
    name: Build all images & upload them as build artifacts
    env:
      DOCKER_BUILDKIT: 1

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Build base image
        run: >
          docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       midstate
          --target    builder

      - name: Build :enable image
        run: >
          docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       simple-qemu:enable
          --target    enable

      - name: Build :<single-arch> images
        run: |
          for arch in $(cat built-architectures.txt); do
            echo "Building simple-qemu:${arch}…"
            docker build . \
              --build-arg QEMU_VERSION=${{QEMU_VERSION}} \
              --build-arg ARCH=${arch} \
              --tag       simple-qemu:${arch} \
              --target    single
          done

      - name: Build :${{QEMU_VERSION}} (all-included) image
        run: >
          docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       simple-qemu:${{QEMU_VERSION}}
          --target    comprehensive

      - name: List all built images
        run: docker images simple-qemu

      - name: Save all images to .tgz files
        run: |
          mkdir -p images/
          for image in $(docker images simple-qemu --format "{{.Repository}}:{{.Tag}}"); do
            FILENAME="$(echo "${image}" | tr : -)"
            docker save "${image}" | gzip > "images/${FILENAME}.tgz"
          done

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Upload built images
        uses: actions/upload-artifact@v1.0.0
        with:
          name: images
          path: images/

      - name: Extract qemu binaries from built image
        run: |
          mkdir -p binaries/
          ID=$(docker create midstate)
          docker cp  "${ID}:/binaries/"  .
          docker rm "${ID}"
          gzip -S "-${{QEMU_VERSION}}.gz" binaries/*

      - name: Print sha256sum of all binaries
        run: sha256sum binaries/*

      - name: Upload built binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binaries/
