  build:
    name: Build all images & upload them as build artifacts
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Extract essence from built-architectures.txt
        run: sed -i  -e 's/\s*#.*$//'  -e '/^\s*$/d'  ./built-architectures.txt

      - name: Build base image
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       midstate
          --file      Dockerfile
          --target    builder

      - name: Build :enable image
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       ${GITHUB_REPOSITORY,,}:enable
          --file      Dockerfile
          --target    enable

      - name: Build :<single-arch> images
        run: |
          for arch in $(cat built-architectures.txt); do
            echo "${arch}"
            DOCKER_BUILDKIT=1 docker build . \
              --build-arg QEMU_VERSION=${{QEMU_VERSION}} \
              --build-arg ARCH=${arch} \
              --tag       ${GITHUB_REPOSITORY,,}:${arch} \
              --file      Dockerfile \
              --target    single
          done

      - name: Build :${{QEMU_VERSION}} (all-included) image
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --build-arg QEMU_VERSION=${{QEMU_VERSION}}
          --tag       ${GITHUB_REPOSITORY,,}:${{QEMU_VERSION}}
          --file      Dockerfile
          --target    comprehensive

      - name: Create extra convenience tags
        run: |
          docker tag ${GITHUB_REPOSITORY,,}:arm     ${GITHUB_REPOSITORY,,}:arm32v7
          docker tag ${GITHUB_REPOSITORY,,}:aarch64 ${GITHUB_REPOSITORY,,}:arm64v8

      - name: List all built images
        run: docker images ${GITHUB_REPOSITORY,,}

      - name: Save all images to .tgz files
        run: |
          mkdir -p images/
          for image in $(docker images ${GITHUB_REPOSITORY,,} --format "{{.Repository}}:{{.Tag}}"); do
            FILENAME="$(echo "${image}" | tr :/ -)"
            docker save "${image}" | gzip > "images/${FILENAME}.tgz"
          done

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Upload built images
        uses: actions/upload-artifact@v1.0.0
        with:
          name: images
          path: images/

      - name: Extract qemu binaries from built image
        run: |
          mkdir -p binaries/
          ID=$(docker create midstate)
          docker cp  "${ID}:/binaries/"  .
          docker rm "${ID}"
          gzip binaries/*

      - name: Print sha256sum of all binaries
        run: sha256sum binaries/*

      - name: Upload built binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binaries/
