  docker-hub-push:
    name: Tag & deploy to Docker Hub.  Only after successful build, and test of a pushed git tag

    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Print Docker version
        run: docker version

      - name: Download all build artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: images

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Load images locally
        run: ls images/ | xargs -I % docker load -i "images/%"

      - name: Setup environment
        run: |
          echo ::set-env name=DOCKER_USER::"${GITHUB_ACTOR,,}"
          echo ::set-env name=DOCKER_SLUG::"${GITHUB_REPOSITORY,,}"

      - name: Version-tag all images
        run: >
          ./scripts/docker-hub-tag.sh \
            simple-qemu \
            "${DOCKER_SLUG}" \
            "${{QEMU_VERSION}}" \
            "enable arm:arm32v7 aarch64:arm64 riscv32 riscv64"

      - name: List all tagged images
        run: docker images "${DOCKER_SLUG}"

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_TOKEN}}" | docker login -u="${DOCKER_USER}" --password-stdin

      - name: Push all images
        run: docker images "${DOCKER_SLUG}" --format "{{.Repository}}:{{.Tag}}" | xargs -I % docker push %

      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.5
        with:
          pass: ${{secrets.DOCKER_TOKEN}}
          description: true
