  docker-push:
    name: Tag & deploy to Docker Hub and Github registry.  Only after successful build, and test of a pushed git tag

    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Print Docker version
        run: docker version

      - name: Download all build artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: images

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Load images locally
        run: ls images/ | xargs -I % docker load -i "images/%"

      - name: Version-tag all images
        run: ./scripts/docker-tag.sh  "${GITHUB_REPOSITORY,,}"  "${{QEMU_VERSION}}"

      - name: List all tagged images
        run: docker images ${GITHUB_REPOSITORY,,}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u="${GITHUB_ACTOR,,}" --password-stdin

      - name: Push all images to Docker Hub
        run: docker images ${GITHUB_REPOSITORY,,} --format "{{.Repository}}:{{.Tag}}" | xargs -I % docker push %

      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.5
        with:
          pass: ${{ secrets.DOCKER_PASS }}
          description: true

      - name: Login to Github Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u="${GITHUB_ACTOR,,}" --password-stdin

      - name: Push all images to Github Registry
        run: |
          for img in $(docker images ${GITHUB_REPOSITORY,,} --format "{{.Repository}}:{{.Tag}}"); do
            docker tag "${img}" "docker.pkg.github.com/${img}"
            docker push "docker.pkg.github.com/${img}"
          done
