  github-registry-push:
    name: Tag & deploy to Github Registry.  Only after successful build, and test of a pushed git tag

    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Print Docker version
        run: docker version

      - name: Download all build artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: images

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Load images locally
        run: ls images/ | xargs -I % docker load -i "images/%"

      - name: Version-tag all images
        run: >
          ./scripts/github-registry-tag.sh \
            simple-qemu \
            "docker.pkg.github.com/meedamian/simple-qemu" \
            "${{QEMU_VERSION}}" \
            "enable arm:arm32v7 aarch64:arm64v8 riscv32 riscv64"

      - name: List all tagged images
        run: docker images "docker.pkg.github.com/meedamian/simple-qemu/*"

      # Temporarily disabled, since it's just borked…
#      - name: Login to Github Registry
#        run: echo "${{ secrets.YET_ANOTHER_GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u="${GITHUB_ACTOR,,}" --password-stdin

#      - name: Push all images
#        run: docker images "docker.pkg.github.com/meedamian/simple-qemu/*" --format "{{.Repository}}:{{.Tag}}" | xargs -I % docker push %
