  test:
    name: Test if running arch-specific images works
    runs-on: ubuntu-18.04
    needs: build
    strategy:
      matrix:
        arch:
          - arm
          - aarch64
#          - riscv32 # Nothing to test it against…
          - riscv64
    steps:
      - uses: actions/checkout@v1

      - name: Download all build artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: images

      - name: Print sha256sum of all images
        run: sha256sum images/*

      - name: Load relevant image locally
        run: docker load -i "images/simple-qemu-${{matrix.arch}}.tgz"

      - name: Enable emulation
        run: docker run --rm --privileged "simple-qemu:${{matrix.arch}}" -p yes

      - name: Try to run arch-specific image
        run: |
          IMAGE="${{matrix.arch}}/alpine"

          if [[ "${{matrix.arch}}" == "riscv64" ]]; then
            IMAGE="carlosedp/debian:sid-riscv64"
          fi

          if [[ "${{matrix.arch}}" == "arm" ]]; then
            IMAGE="arm32v7/alpine"
          fi

          docker run ${IMAGE} uname -a

      - name: Verify that git tag build is the same as used for build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          GIT_VER="$(echo ${GITHUB_REF} | awk -F/ '{print $NF}')"

          if [ "${GIT_VER}" != "${{QEMU_VERSION}}" ]; then
            printf "\nVersion mismatch!  Tagged as %s, while file claims %s\n\n" "${GIT_VER}" "${{QEMU_VERSION}}"
            exit 1
          fi
